### ISSUE TITLE
Question: NOR flash

### ISSUE THREAD

**Issue by cppcoffee** [bestouff/fw_env#1]
This tool is really great.

I'm going to use it to read the uboot-env, If I use NOR flash can I ignore those three TODO things?

```
 full config file (/etc/fw_env.config) parsing
 handle bad blocks in flash
 handle flags in redundant blocks
```

**Comment by bestouff** [comment]
Well I only ever used it on NAND flash chips (eMMC) but as long as you only read from the flash that shouldn't cause any trouble.

**Comment by cppcoffee** [comment]
Thank you for the answer.
